missing include
>getopt.c:386:30: error: call to undeclared library function 'strcmp' with type 'int (const char *, const char *)';
>      ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
>  386 |       if (optind != argc && !strcmp (argv[optind], "--"))
>      |                              ^

Signed-off-by: Nicolas PARLANT <nicolas.parlant@parhuet.fr>